FROM oven/bun:latest

WORKDIR /usr/src/app

COPY ./packages  ./packages
COPY ./bun.lock  ./bun.lock
COPY ./package.json ./package.json 

COPY  ./turbo.json   ./turbo.json

COPY ./apps/https   ./apps/https


RUN bun install 
RUN bun run db:generate

EXPOSE 3002


CMD ["bun" , "run" , "start:https"]